# database.py

CS_COURSES = {
    "CSI3102": {
        "name": "Artificial Intelligence",
        "workload": "Medium",
        "difficulty": "Medium",
        "professor": "Dr. J. Yeo",
        "review": "Incredibly engaging, highly structured coding projects. Great for machine learning tracks.",
        "keywords": ["ai", "machine learning", "python", "coding"]
    },
    "CSI2103": {
        "name": "Operating Systems",
        "workload": "Heavy",
        "difficulty": "High",
        "professor": "Dr. T. Kim",
        "review": "Very heavy workload with demanding C programming labs, but absolutely critical for core systems understanding.",
        "keywords": ["systems", "c", "os", "heavy", "low-level"]
    },
    "CSI2101": {
        "name": "Discrete Structures",
        "workload": "Medium",
        "difficulty": "High",
        "professor": "Dr. S. Lee",
        "review": "Very theoretical and math-heavy. Weekly problem sets, strict grading but clear lectures.",
        "keywords": ["math", "theory", "proofs", "discrete"]
    },
    "CAS1102-01": {
        "name": "OBJECT-ORIENTED PROGRAMMING",
        "workload": "Medium",
        "difficulty": "Medium",
        "professor": "Lee Sheayun",
        "language medium": "Korean",
        "lecture type": "In-person",
        "major requirement": True,
        "major basic": True,
        "major elective": False, 
        "major year": 1,
        "credits": 3, 
        "time": "Tue 2, Thu 2,3",
        "location": "EngHD504",
        "grading scheme": "",
        "evaluation type": "relative",
        "prerequisites": [],
        "added by in ETA": "", 
        "review": "",
        "review from other courses": "",
        "keywords": ["oop", "programming", "object-oriented", "java", "c++"]
    },
    "CAS2101-01": {
        "name": "DISCRETE MATHEMATICS",
        "workload": "Medium",
        "difficulty": "Medium",
        "professor": "Lee Jinkyu",
        "language medium": "English",
        "lecture type": "In-person",
        "major requirement": True,
        "major basic": True,
        "major elective": False, 
        "major year": 2,
        "credits": 3, 
        "time": "Tue 8,9, Thu 7",
        "location": "EngHD508",
        "grading scheme": "",
        "evaluation type": "absolute",
        "prerequisites": [],
        "added by in ETA": "", 
        "review": "",
        "review from other courses": "",
        "keywords": ["math", "discrete", "logic", "proofs"]
    },
    "CAS2101-02": {
        "name": "DISCRETE MATHEMATICS",
        "workload": "Medium",
        "difficulty": "Medium",
        "professor": "Lee Jongmin",
        "language medium": "English",
        "lecture type": "In-person",
        "major requirement": True,
        "major basic": True,
        "major elective": False, 
        "major year": 2,
        "credits": 3, 
        "time": "Tue 8,9, Thu 7",
        "location": "EngHD408",
        "grading scheme": "",
        "evaluation type": "absolute",
        "prerequisites": [],
        "added by in ETA": "", 
        "review": "",
        "review from other courses": "",
        "keywords": ["math", "discrete", "logic", "proofs"]
    },
    "CAS2103-01": {
        "name": "DATA STRUCTURE",
        "workload": "Medium",
        "difficulty": "Medium",
        "professor": "An Hyung-Chan",
        "language medium": "English",
        "lecture type": "In-person",
        "major requirement": True,
        "major basic": True,
        "major elective": False, 
        "major year": 1,
        "credits": 3, 
        "time": "Wed 5, Fri 5,6",
        "location": "EngHD408",
        "grading scheme": "",
        "evaluation type": "absolute",
        "prerequisites": [],
        "added by in ETA": "", 
        "review": "",
        "review from other courses": "",
        "keywords": ["data structures", "algorithms", "arrays", "trees", "coding"]
    },
    "CAS2103-02": {
        "name": "DATA STRUCTURE",
        "workload": "Medium",
        "difficulty": "Medium",
        "professor": "HWANG SEONG JAE",
        "language medium": "English",
        "lecture type": "In-person",
        "major requirement": True,
        "major basic": True,
        "major elective": False, 
        "major year": 1,
        "credits": 3, 
        "time": "Wed 5, Fri 5,6",
        "location": "EngHD504",
        "grading scheme": "",
        "evaluation type": "absolute",
        "prerequisites": [],
        "added by in ETA": "", 
        "review": "",
        "review from other courses": "",
        "keywords": ["data structures", "algorithms", "arrays", "trees", "coding"]
    },
    "CAS2103-03": {
        "name": "DATA STRUCTURE",
        "workload": "Medium",
        "difficulty": "Medium",
        "professor": "Kim Jieung",
        "language medium": "English",
        "lecture type": "In-person",
        "major requirement": False,
        "major basic": True,
        "major elective": False, 
        "major year": 1,
        "credits": 3, 
        "time": "Wed 5, Fri 5,6",
        "location": "EngHD508",
        "grading scheme": "",
        "evaluation type": "absolute",
        "prerequisites": [],
        "added by in ETA": "", 
        "review": "",
        "review from other courses": "",
        "keywords": ["data structures", "algorithms", "arrays", "trees", "coding"]
    },
    "CAS2106-01": {
        "name": "INTRODUCTION TO COMPUTER SCIENCE",
        "workload": "Medium",
        "difficulty": "Medium",
        "professor": "Park Sang Hyun",
        "language medium": "Korean",
        "lecture type": "On-Off Blended (Video Recorded)",
        "major requirement": False,
        "major basic": False,
        "major elective": True, 
        "major year": 2,
        "credits": 3, 
        "time": "Tue 7 / Thu 12,13",
        "location": "EngHD504 / Pre-recorded lecture",
        "grading scheme": "",
        "evaluation type": "relative",
        "prerequisites": [],
        "added by in ETA": "", 
        "review": "",
        "review from other courses": "",
        "keywords": ["cs", "computer science", "intro", "foundations"]
    },
    "CAS2109-01": {
        "name": "INTERNET PROGRAMMING",
        "workload": "Medium",
        "difficulty": "Medium",
        "professor": "Lee, Kyong Ho",
        "language medium": "Korean",
        "lecture type": "On-Off Blended (Video Recorded)",
        "major requirement": False,
        "major basic": False,
        "major elective": True, 
        "major year": 2,
        "credits": 3, 
        "time": "Tue 5,6 / Thu 11",
        "location": "EngHD504 / Pre-recorded lecture",
        "grading scheme": "",
        "evaluation type": "relative",
        "prerequisites": [],
        "added by in ETA": "", 
        "review": "",
        "review from other courses": "",
        "keywords": ["web", "internet", "html", "css", "javascript", "programming"]
    },
    "CAS3101-01": {
        "name": "OPERATING SYSTEM",
        "workload": "Medium",
        "difficulty": "Medium",
        "professor": "Cha, Hojung",
        "language medium": "Korean",
        "lecture type": "In-person",
        "major requirement": True,
        "major basic": False,
        "major elective": False, 
        "major year": 3,
        "credits": 3, 
        "time": "Mon 7,8, Wed 8",
        "location": "EngHD504",
        "grading scheme": "",
        "evaluation type": "relative",
        "prerequisites": [],
        "added by in ETA": "", 
        "review": "",
        "review from other courses": "",
        "keywords": ["os", "operating system", "kernel", "processes", "threads"]
    },
    "CAS3101-02": {
        "name": "OPERATING SYSTEM",
        "workload": "Medium",
        "difficulty": "Medium",
        "professor": "JEONG JINKYU",
        "language medium": "Korean",
        "lecture type": "In-person",
        "major requirement": True,
        "major basic": False,
        "major elective": False, 
        "major year": 3,
        "credits": 3, 
        "time": "Mon 7,8, Wed 8",
        "location": "EngHB039",
        "grading scheme": "",
        "evaluation type": "relative",
        "prerequisites": [],
        "added by in ETA": "", 
        "review": "",
        "review from other courses": "",
        "keywords": ["os", "operating system", "kernel", "processes", "threads"]
    },
    "CAS3102-01": {
        "name": "ARCHITECTURE OF COMPUTERS",
        "workload": "Medium",
        "difficulty": "Medium",
        "professor": "Lee Kyoungwoo",
        "language medium": "Korean",
        "lecture type": "On-Off Blended (Flipped Classroom)",
        "major requirement": True,
        "major basic": False,
        "major elective": False, 
        "major year": 3,
        "credits": 3, 
        "time": "Mon 5,6 / Wed 6",
        "location": "EngHD504 / Pre-recorded lecture",
        "grading scheme": "",
        "evaluation type": "relative",
        "prerequisites": [],
        "added by in ETA": "", 
        "review": "Flipped classroom layout requires pre-class video viewing before live participation.",
        "review from other courses": "",
        "keywords": ["architecture", "hardware", "mips", "cpu", "computer architecture"]
    }
}