# database.py

CS_COURSES = {
    "CSI3102": {
        "name": "Artificial Intelligence",
        "workload": "Medium",
        "difficulty": "Medium",
        "professor": "Dr. J. Yeo",
        "review": "Incredibly engaging, highly structured coding projects. Great for machine learning tracks.",
        "keywords": ["ai", "machine learning", "python", "coding"]
    },
    "CSI2103": {
        "name": "Operating Systems",
        "workload": "Heavy",
        "difficulty": "High",
        "professor": "Dr. T. Kim",
        "review": "Very heavy workload with demanding C programming labs, but absolutely critical for core systems understanding.",
        "keywords": ["systems", "c", "os", "heavy", "low-level"]
    },
    "CSI2101": {
        "name": "Discrete Structures",
        "workload": "Medium",
        "difficulty": "High",
        "professor": "Dr. S. Lee",
        "review": "Very theoretical and math-heavy. Weekly problem sets, strict grading but clear lectures.",
        "keywords": ["math", "theory", "proofs", "discrete"]
    },
    "CAS1102-01": {
        "name": "OBJECT-ORIENTED PROGRAMMING",
        "workload": "Medium",
        "difficulty": "Medium",
        "professor": "Lee Sheayun",
        "language medium": "Korean",
        "lecture type": "In-person",
        "major requirement": True,
        "major basic": True,
        "major elective": False, 
        "major year": 1,
        "credits": 3, 
        "time": "Tue 2, Thu 2,3",
        "location": "EngHD504",
        "grading scheme": "",
        "evaluation type": "relative",
        "prerequisites": [],
        "added by in ETA": "", 
        "review": "",
        "review from other courses": "",
        "keywords": ["oop", "programming", "object-oriented", "java", "c++"]
    },
    "CAS2101-01": {
        "name": "DISCRETE MATHEMATICS",
        "workload": "Medium",
        "difficulty": "Medium",
        "professor": "Lee Jinkyu",
        "language medium": "English",
        "lecture type": "In-person",
        "major requirement": True,
        "major basic": True,
        "major elective": False, 
        "major year": 2,
        "credits": 3, 
        "time": "Tue 8,9, Thu 7",
        "location": "EngHD508",
        "grading scheme": "",
        "evaluation type": "absolute",
        "prerequisites": [],
        "added by in ETA": "", 
        "review": "",
        "review from other courses": "",
        "keywords": ["math", "discrete", "logic", "proofs"]
    },
    "CAS2101-02": {
        "name": "DISCRETE MATHEMATICS",
        "workload": "Medium",
        "difficulty": "Medium",
        "professor": "Lee Jongmin",
        "language medium": "English",
        "lecture type": "In-person",
        "major requirement": True,
        "major basic": True,
        "major elective": False, 
        "major year": 2,
        "credits": 3, 
        "time": "Tue 8,9, Thu 7",
        "location": "EngHD408",
        "grading scheme": "",
        "evaluation type": "absolute",
        "prerequisites": [],
        "added by in ETA": "", 
        "review": "",
        "review from other courses": "",
        "keywords": ["math", "discrete", "logic", "proofs"]
    },
    "CAS2103-01": {
        "name": "DATA STRUCTURE",
        "workload": "Medium",
        "difficulty": "Medium",
        "professor": "An Hyung-Chan",
        "language medium": "English",
        "lecture type": "In-person",
        "major requirement": True,
        "major basic": True,
        "major elective": False, 
        "major year": 1,
        "credits": 3, 
        "time": "Wed 5, Fri 5,6",
        "location": "EngHD408",
        "grading scheme": "",
        "evaluation type": "absolute",
        "prerequisites": [],
        "added by in ETA": "", 
        "review": "",
        "review from other courses": "",
        "keywords": ["data structures", "algorithms", "arrays", "trees", "coding"]
    },
    "CAS2103-02": {
        "name": "DATA STRUCTURE",
        "workload": "Medium",
        "difficulty": "Medium",
        "professor": "HWANG SEONG JAE",
        "language medium": "English",
        "lecture type": "In-person",
        "major requirement": True,
        "major basic": True,
        "major elective": False, 
        "major year": 1,
        "credits": 3, 
        "time": "Wed 5, Fri 5,6",
        "location": "EngHD504",
        "grading scheme": "",
        "evaluation type": "absolute",
        "prerequisites": [],
        "added by in ETA": "", 
        "review": "",
        "review from other courses": "",
        "keywords": ["data structures", "algorithms", "arrays", "trees", "coding"]
    },
    "CAS2103-03": {
        "name": "DATA STRUCTURE",
        "workload": "Medium",
        "difficulty": "Medium",
        "professor": "Kim Jieung",
        "language medium": "English",
        "lecture type": "In-person",
        "major requirement": False,
        "major basic": True,
        "major elective": False, 
        "major year": 1,
        "credits": 3, 
        "time": "Wed 5, Fri 5,6",
        "location": "EngHD508",
        "grading scheme": "",
        "evaluation type": "absolute",
        "prerequisites": [],
        "added by in ETA": "", 
        "review": "",
        "review from other courses": "",
        "keywords": ["data structures", "algorithms", "arrays", "trees", "coding"]
    },
    "CAS2106-01": {
        "name": "INTRODUCTION TO COMPUTER SCIENCE",
        "workload": "Medium",
        "difficulty": "Medium",
        "professor": "Park Sang Hyun",
        "language medium": "Korean",
        "lecture type": "On-Off Blended (Video Recorded)",
        "major requirement": False,
        "major basic": False,
        "major elective": True, 
        "major year": 2,
        "credits": 3, 
        "time": "Tue 7 / Thu 12,13",
        "location": "EngHD504 / Pre-recorded lecture",
        "grading scheme": "",
        "evaluation type": "relative",
        "prerequisites": [],
        "added by in ETA": "", 
        "review": "",
        "review from other courses": "",
        "keywords": ["cs", "computer science", "intro", "foundations"]
    },
    "CAS2109-01": {
        "name": "INTERNET PROGRAMMING",
        "workload": "Medium",
        "difficulty": "Medium",
        "professor": "Lee, Kyong Ho",
        "language medium": "Korean",
        "lecture type": "On-Off Blended (Video Recorded)",
        "major requirement": False,
        "major basic": False,
        "major elective": True, 
        "major year": 2,
        "credits": 3, 
        "time": "Tue 5,6 / Thu 11",
        "location": "EngHD504 / Pre-recorded lecture",
        "grading scheme": "",
        "evaluation type": "relative",
        "prerequisites": [],
        "added by in ETA": "", 
        "review": "",
        "review from other courses": "",
        "keywords": ["web", "internet", "html", "css", "javascript", "programming"]
    },
    "CAS3101-01": {
        "name": "OPERATING SYSTEM",
        "workload": "Medium",
        "difficulty": "Medium",
        "professor": "Cha, Hojung",
        "language medium": "Korean",
        "lecture type": "In-person",
        "major requirement": True,
        "major basic": False,
        "major elective": False, 
        "major year": 3,
        "credits": 3, 
        "time": "Mon 7,8, Wed 8",
        "location": "EngHD504",
        "grading scheme": "",
        "evaluation type": "relative",
        "prerequisites": [],
        "added by in ETA": "", 
        "review": "",
        "review from other courses": "",
        "keywords": ["os", "operating system", "kernel", "processes", "threads"]
    },
    "CAS3101-02": {
        "name": "OPERATING SYSTEM",
        "workload": "Medium",
        "difficulty": "Medium",
        "professor": "JEONG JINKYU",
        "language medium": "Korean",
        "lecture type": "In-person",
        "major requirement": True,
        "major basic": False,
        "major elective": False, 
        "major year": 3,
        "credits": 3, 
        "time": "Mon 7,8, Wed 8",
        "location": "EngHB039",
        "grading scheme": "",
        "evaluation type": "relative",
        "prerequisites": [],
        "added by in ETA": "", 
        "review": "",
        "review from other courses": "",
        "keywords": ["os", "operating system", "kernel", "processes", "threads"]
    },
    "CAS3102-01": {
        "name": "ARCHITECTURE OF COMPUTERS",
        "workload": "Medium",
        "difficulty": "Medium",
        "professor": "Lee Kyoungwoo",
        "language medium": "Korean",
        "lecture type": "On-Off Blended (Flipped Classroom)",
        "major requirement": True,
        "major basic": False,
        "major elective": False, 
        "major year": 3,
        "credits": 3, 
        "time": "Mon 5,6 / Wed 6",
        "location": "EngHD504 / Pre-recorded lecture",
        "grading scheme": "",
        "evaluation type": "relative",
        "prerequisites": [],
        "added by in ETA": "", 
        "review": "Flipped classroom layout requires pre-class video viewing before live participation.",
        "review from other courses": "",
        "keywords": ["architecture", "hardware", "mips", "cpu", "computer architecture"]
    },
    
    "CAS4102-01-00": {
        "name": "인공지능종합설계 (AI Capstone Design)",
        "workload": "Medium",
        "difficulty": "Medium",
        "professor": "이동신 (B. Lee)",
        "language medium": "Korean (no explicit English label)",
        "lecture type": "In-person",
        "major requirement": True,
        "major basic": False,
        "major elective": False,
        "major year": 3,
        "credits": 3,
        "time": "Wed 4:00–5:00 PM, Fri 4:00–6:00 PM",
        "location": "공D508",
        "grading scheme": "70% team projects, 10% attendance, 20% other",
        "evaluation type": "absolute",
        "prerequisites": [],
        "added by in ETA": "",
        "review": "",
        "review from other courses": "",
        "keywords": ["capstone design", "team project", "AI system design", "research trends", "exhibition"]
    },
    
    "CAS4108-01-00": {
        "name": "데이터프라이버시학 (Data Privacy)",
        "workload": "Medium",
        "difficulty": "Medium",
        "professor": "노일버트 (Albert No)",
        "language medium": "English",
        "lecture type": "In-person",
        "major requirement": False,
        "major basic": False,
        "major elective": True,
        "major year": 3,
        "credits": 3,
        "time": "Tue 12:00–1:00 PM, Thu 1:00–3:00 PM",
        "location": "공D508",
        "grading scheme": "45% midterm, 45% final, 10% individual assignments",
        "evaluation type": "absolute",
        "prerequisites": ["Probability theory", "Linear algebra", "Calculus"],
        "added by in ETA": "20",
        "review": "responsive to questions, good teaching quality, high difficulty, professor good at explaining, test questions are mostly proof questions, taking courses like probability theory, linear algebra and calculus will help a lot, fair grading distribution",
        "review from other courses": "",
        "keywords": ["differential privacy", "generative diffusion models", "large language models", "privacy", "federated learning", "memorization", "unlearning", "watermarking"]
    },

    "CAS4109-01-00": {
        
    "name": "컴퓨터보안학 (Computer Security)",
    "workload": "High",
    "difficulty": "High",
    "professor": "송도경 (Dokyung Song)",
    "language medium": "English",
    "lecture type": "In-person",
    "major requirement": False,
    "major basic": False,
    "major elective": True,
    "major year": 3,
    "credits": 3,
    "time": "Schedule ambiguous (listed as 3/7/7/12,13 - check syllabus)",
    "location": "공D408 / online video (duplicate registration not allowed)",
    "grading scheme": "20% midterm, 20% final, 55% individual assignments, 5% attendance",
    "evaluation type": "absolute",
    "prerequisites": ["Operating Systems", "Computer Architecture"],
    "added by in ETA": "",
    "review": "",
    "review from other courses": "",
    "keywords": ["computer security", "threat modeling", "access control", "authentication", "cryptography", "software security", "hardware security", "attack payloads", "defensive programming"]
    
    },

    "CAS4119-01-00" : {
    "name": "멀티코어및GPU프로그래밍 (Multi-core and GPU Programming)",
    "workload": "High",
    "difficulty": "High",
    "professor": "박영준 (Yongjun Park)",
    "language medium": "English",
    "lecture type": "In-person",
    "major requirement": False,
    "major basic": False,
    "major elective": True,
    "major year": 3,
    "credits": 3,
    "time": "Wed 11:00–12:00 PM, Fri 11:00–1:00 PM",
    "location": "공D504",
    "grading scheme": "Grading scheme not specified in visible text",
    "evaluation type": "absolute",
    "prerequisites": ["OS (Operating Systems)", "CA (Computer Architecture)", "Algorithm"],
    "added by in ETA": "",
    "review": "",
    "review from other courses": "",
    "keywords": ["multi-core", "GPU", "CUDA", "Pthread", "openMP", "parallel programming", "matrix multiplication", "reduction", "deep learning kernels"]
    },
    
    "CAS4127-01-00" : {
    "name": "인간-인공지능상호작용학 (Human-AI Interaction)",
    "workload": "High",
    "difficulty": "Medium",
    "professor": "김대현 (Daehyun Kim)",
    "language medium": "English",
    "lecture type": "In-person",
    "major requirement": False,
    "major basic": False,
    "major elective": True,
    "major year": 3,
    "credits": 3,
    "time": "Tue/Wed/Thu? Schedule ambiguous (listed as '3,2,3,목1')",
    "location": "공D408",
    "grading scheme": "40% individual assignments, 30% team projects, 10% attendance, 20% participation",
    "evaluation type": "absolute",
    "prerequisites": [],
    "added by in ETA": "",
    "review": "",
    "review from other courses": "",
    "keywords": ["human-AI interaction", "HCI", "AI collaboration", "user modeling", "simulating human behavior", "LLM", "creativity", "education"]
    },

    "CAS4133-01-00" : {
    "name": "거대언어모델학 (Large Language Models)",
    "workload": "High",
    "difficulty": "High",
    "professor": "김재형 (Jaehyung Kim)",
    "language medium": "English",
    "lecture type": "In-person",
    "major requirement": False,
    "major basic": False,
    "major elective": True,
    "major year": 3,
    "credits": 3,
    "time": "Mon 1:00–3:00 PM, Wed 2:00–3:00 PM",
    "location": "공D508",
    "grading scheme": "20% midterm, 30% final, 40% individual assignments, 10% attendance",
    "evaluation type": "absolute",
    "prerequisites": ["Machine learning", "Deep learning"],
    "added by in ETA": "",
    "review": "",
    "review from other courses": "",
    "keywords": ["large language models", "LLM", "pre-training", "scaling laws", "alignment", "instruction tuning", "RLHF", "RAG", "AI agents", "multi-modality"]

    },

    "CAS4150-01-00" : {
    "name": "데이터시각화입문 (Introduction to Data Visualization)",
    "workload": "Medium",
    "difficulty": "Medium",
    "professor": "강민석 (Minsuk Kang)",
    "language medium": "English",
    "lecture type": "In-person",
    "major requirement": False,
    "major basic": False,
    "major elective": True,
    "major year": 3,
    "credits": 3,
    "time": "Tue 12:00–1:00 PM, Thu 3:00–5:00 PM",
    "location": "동영상콘텐츠 / 공D408 (video content + room D408)",
    "grading scheme": "25% midterm, 25% final, 20% individual assignments, 20% team projects, 10% other",
    "evaluation type": "absolute",
    "prerequisites": ["Basic programming knowledge", "HTML/CSS (recommended)"],
    "added by in ETA": "",
    "review": "",
    "review from other courses": "",
    "keywords": ["data visualization", "interactive visualization", "JavaScript", "D3", "Tableau", "exploratory data analysis", "human-centered design", "perception", "color"]
    },
    
    "MAT2013-03-00" : {
    "name": "확률통계학 (Probability and Statistics)",
    "workload": "Medium",
    "difficulty": "Medium",
    "professor": "최장열 (Jangyeol Choi)",
    "language medium": "Korean (no explicit English label)",
    "lecture type": "In-person",
    "major requirement": True,
    "major basic": True,
    "major elective": False,
    "major year": 2,
    "credits": 3,
    "time": "Mon 4:00–6:00 PM, Wed 5:00–6:00 PM",
    "location": "공학월170E",
    "grading scheme": "Not specified in visible text",
    "evaluation type": "relative",
    "prerequisites": [],
    "added by in ETA": "",
    "review": "",
    "review from other courses": "",
    "keywords": ["probability", "statistics", "random variables", "probability distributions", "expectation", "conditional probability", "joint density", "marginal density", "MGF"]
    }, 

    "MAT2013-04-00" : {
    "name": "확률통계학 (Probability and Statistics)",
    "workload": "Medium",
    "difficulty": "Medium",
    "professor": "김현정 (Hyunjung Kim)",
    "language medium": "Korean (no explicit English label)",
    "lecture type": "In-person",
    "major requirement": True,
    "major basic": True,
    "major elective": False,
    "major year": 2,
    "credits": 3,
    "time": "Fri 9:00 AM – 12:00 PM",
    "location": "공D408",
    "grading scheme": "Not specified in visible text",
    "evaluation type": "relative",
    "prerequisites": [],
    "added by in ETA": "",
    "review": "",
    "review from other courses": "",
    "keywords": ["probability", "statistics", "random variables", "discrete distributions", "continuous distributions", "central limit theorem", "expected value", "variance", "regression analysis"]
    },

    "MAT2011-03-00" : {
    "name": "선형대수와그응용 (Linear Algebra and Its Applications)",
    "workload": "Medium",
    "difficulty": "Medium",
    "professor": "최장열 (Jangyeol Choi)",
    "language medium": "Korean (no explicit English label)",
    "lecture type": "In-person",
    "major requirement": True,
    "major basic": True,
    "major elective": False,
    "major year": 1,
    "credits": 3,
    "time": "Mon 6:00–8:00 PM, Wed 7:00–8:00 PM",
    "location": "공학월170E",
    "grading scheme": "Not specified in visible text",
    "evaluation type": "relative",
    "prerequisites": [],
    "added by in ETA": "",
    "review": "",
    "review from other courses": "",
    "keywords": ["linear algebra", "vector space", "linear independence", "basis", "linear operators", "matrices", "eigenvalues", "eigenvectors"]
    },

    "CAS4151-01-00" : {
    "name": "SW-AI비즈니스응용설계 (SW-AI Business Application Design)",
    "workload": "Medium",
    "difficulty": "Medium",
    "professor": "김현수 (Hyunsoo Kim)",
    "language medium": "Korean (no explicit English label)",
    "lecture type": "In-person",
    "major requirement": True,
    "major basic": False,
    "major elective": False,
    "major year": 4,
    "credits": 3,
    "time": "Wed 2:00–3:00 PM, Fri 2:00–4:00 PM",
    "location": "공A343 / 공D507",
    "grading scheme": "50% individual assignments, 20% attendance, 30% other",
    "evaluation type": "absolute",
    "prerequisites": ["Basic coding skills (coding methods not taught in class)"],
    "added by in ETA": "",
    "review": "",
    "review from other courses": "",
    "keywords": ["business", "AI", "SW", "problem solving", "market testing", "MVP", "POC", "growth hacking", "self-directed learning"]
    }, 

    "CAS4160-01-00" : {
    "name": "강화학습 (Reinforcement Learning)",
    "workload": "High",
    "difficulty": "High",
    "professor": "이영운 (Youngwoon Lee)",
    "language medium": "English",
    "lecture type": "In-person",
    "major requirement": True,
    "major basic": False,
    "major elective": False,
    "major year": 3,
    "credits": 3,
    "time": "Wed 1:00–2:00 PM, Fri 7:00–9:00 PM",
    "location": "공D504 / online video (duplicate registration not allowed)",
    "grading scheme": "30% midterm, 30% final, 35% individual assignments, 5% other",
    "evaluation type": "absolute",
    "prerequisites": ["Machine Learning", "Deep Learning", "PyTorch"],
    "added by in ETA": "",
    "review": "",
    "review from other courses": "",
    "keywords": ["reinforcement learning", "deep RL", "policy gradients", "actor-critic", "PPO", "Q-learning", "offline RL", "model-based RL", "inverse RL", "RLHF", "PyTorch"]
    }, 

    "CAS4131-01-00" : {
    "name": "커넥티드플랫폼이론과실제 (Connected Platform Theory and Practice)",
    "workload": "Medium",
    "difficulty": "Medium",
    "professor": "이경우 (Kyoungwoo Lee)",
    "language medium": "Korean (no explicit English label)",
    "lecture type": "In-person",
    "major requirement": True,
    "major basic": False,
    "major elective": False,
    "major year": 3,
    "credits": 3,
    "time": "Mon 11:00 AM – 2:00 PM",
    "location": "공D508",
    "grading scheme": "Not specified in visible text",
    "evaluation type": "absolute",
    "prerequisites": [],
    "added by in ETA": "",
    "review": "",
    "review from other courses": "",
    "keywords": ["webOS", "LG Smart TV", "embedded platform", "connected devices", "voice recognition", "AI", "open source", "DevOps", "media"]
    },
}
