# database.py

CS_COURSES = {
    "CAS1102-01": {
        "name": "객체지향프로그래밍 (OBJECT-ORIENTED PROGRAMMING)",
        "workload": "Medium",
        "difficulty": "Medium",
        "professor": "이시윤 (Lee Sheayun)",
        "language medium": "Korean",
        "lecture type": "In-person",
        "major requirement": True,
        "major basic": True,
        "major elective": False, 
        "major year": 1,
        "credits": 3, 
        "time": "Tue 2, Thu 2,3",
        "location": "공D504 (EngHD504)",
        "grading scheme": "30% midterm, 40% final, 25% individual assignment, 5% attendance",
        "evaluation type": "relative",
        "prerequisites": ["Computer Programming", "Basic Coding Skills"],
        "added by in ETA": "74",
        "max students" : "",
        "review point" : "0.00/5.00",
        "review": "No previous reviews.",
        "review from other courses": "Cloud Computing: Decent lectures and labs, but report grading is highly subjective and feels heavily based on word count. Exams are unpredictable, testing obscure slide details rather than core programming concepts. Software Engineering: Heavily theoretical and conceptual, focusing on management principles rather than practical development skills (lacks Git, design patterns, or automation). Slide info density is low, exams are unpredictable, and grading is very strict (high exam scores still result in an A-)." ,
        "keywords": ["oop", "programming", "object-oriented", "c++", "adt", "classes", "inheritance", "polymorphism", "virtual functions"]
    },
    "CAS2101-01": {
        "name": "이산구조 (DISCRETE MATHEMATICS)",
        "workload": "Medium",
        "difficulty": "Medium",
        "professor": "이진규 (Lee Jinkyu)",
        "language medium": "English",
        "lecture type": "In-person",
        "major requirement": True,
        "major basic": True,
        "major elective": False, 
        "major year": 2,
        "credits": 3, 
        "time": "Tue 8,9, Thu 7",
        "location": "공D508 (EngHD508)",
        "grading scheme": "20% midterm, 40% final, 20% individual assignment, 10% attendance, 10% other",
        "evaluation type": "absolute",
        "prerequisites": ["Basic Highschool Mathematics"],
        "added by in ETA": "70", 
        "review point" : "0.00/5.00",
        "review": "No previous reviews.",
        "review from other courses": "Real-time System: Highly structured lectures with clear step-by-step explanations. Exams are manageable but sometimes test minor, seemingly unimportant details, and the final exam requires strong intuition. Workload is steady, consisting of weekly small assignments, one major project, and three presentations.",
        "keywords": ["math", "discrete", "logic", "proofs", "sets", "calculus", "induction", "recursion", "permutation", "combination", "graphs"]
        
    },
    "CAS2101-02": {
        "name": "이산구조 (DISCRETE MATHEMATICS)",
        "workload": "Medium",
        "difficulty": "Medium",
        "professor": "이종민 (Lee Jongmin)",
        "language medium": "English",
        "lecture type": "In-person",
        "major requirement": True,
        "major basic": True,
        "major elective": False, 
        "major year": 2,
        "credits": 3, 
        "time": "Tue 8,9, Thu 7",
        "location": "공D408 (EngHD408)",
        "grading scheme": "30% midterm, 30% final, 40% individual assignment",
        "evaluation type": "absolute",
        "prerequisites": [],
        "review point" : "4.75/5.00",
        "review": "Absolute grading with no attendance points. Consists of two exams and four very generously graded assignments that help buffer your final grade. Multiple-choice exam questions (especially 'select all that apply') are quite difficult, but essay and T/F questions are manageable as many come directly from assignments. Content touches superficially on logic, set theory, and graph theory. Lecture quality can feel average or lagging behind the polished slide notes, making some difficult topics tough to self-study.",
        "review from other courses": "Global Business / International Business: The professor is incredibly sweet, deeply caring, speaks fluent English, and gives exceptionally generous grades. Individual tasks and exams have a very low workload and are easy to pass just by reviewing the slides. However, random group assignments aimed at international diversity are a major headache, making your experience heavily dependent on team luck.\nSemiconductor Industry: An incredibly easy, high-scoring course with general education-level difficulty, though you may have to travel to the Songdo campus for exams.\nComputer-Aided Design: Presentations are conducted by section; picking a section with fewer people lets you get through them much faster.",
        "keywords": ["math", "discrete", "logic", "proofs", "sets", "calculus", "induction", "recursion", "permutation", "combination", "graphs"]
    },
    "CAS2103-01": {
        "name": "자료구조 (DATA STRUCTURE)",
        "workload": "Medium",
        "difficulty": "Medium",
        "professor": "안형찬 (An Hyung-Chan)",
        "language medium": "English",
        "lecture type": "In-person",
        "major requirement": True,
        "major basic": True,
        "major elective": False, 
        "major year": 1,
        "credits": 3, 
        "time": "Wed 5, Fri 5,6",
        "location": "공D408 (EngHD408)",
        "grading scheme": "35% midterm, 40% final, 20% individual assignment, 5% attendance",
        "evaluation type": "absolute",
        "prerequisites": ["Computer Programming", "Object Oriented Programming"],
        "added by in ETA": "74",
        "review point" : "4.31/5.00", 
        "review": "Excellent, highly clear, and fluent English lectures; the professor answers questions with great sincerity, offering step-by-step help. Attendance is strictly by-the-book. Exams are difficult and heavily feature handwritten manual coding based on PPT code and pseudocode. Assignment grading can be strict and feedback is often late, but the final course grading scale is surprisingly generous, making it highly rewarding.",
        "review from other courses": "Artificial Intelligence Algorithm: Online/open class with dense material and a high volume of weekly assignments. The final quiz is very tough. The professor is noted as extremely strict, rarely checks email, and implements rigid grading cutoffs, though the course provides a solid foundation in basic data structures and algorithms.",
        "keywords": ["data structures", "algorithms", "java", "complexity", "asymptotic notation", "stacks", "queues", "lists", "trees", "graphs", "sorting", "hashing"]
    },
    "CAS2103-02": {
        "name": "자료구조 (DATA STRUCTURE)",
        "workload": "Medium",
        "difficulty": "Medium",
        "professor": "황성재 (Hwang Seong Jae)",
        "language medium": "English",
        "lecture type": "In-person",
        "major requirement": True,
        "major basic": True,
        "major elective": False, 
        "major year": 1,
        "credits": 3, 
        "time": "Wed 5, Fri 5,6",
        "location": "공D504 (EngHD504)",
        "grading scheme": "30% midterm, 30% final, 30% individual assignment, 10% attendance",
        "evaluation type": "absolute",
        "prerequisites": ["Computer Programming", "Object Oriented Programming"],
        "added by in ETA": "92", 
        "review point" : "4.96/5.00",
        "review": "Widely considered a flawless, legendary 'GOAT' course. Professor Hwang has top-tier teaching skills, exceptional English fluency, and an incredibly kind, accommodating personality. He uploads video recordings of every lecture along with dedicated video guides and detailed specs for the 4 coding assignments. While the first assignment is a bit tough, the rest are highly manageable and informative. Exams are challenging but very fair if you study the concepts. Grading is phenomenally generous, heavily rewarding effort and solid assignment completion.",
        "review from other courses": "Computer Vision: High-quality, practical course with user-friendly assignments and no midterm. The final exam covers basic, essential concepts and is very manageable. Grading is highly generous (e.g., 38% A+, 22% A0).\nIntroduction to Computing: Enriching seminar-style class showcasing graduate research topics. Held at an inconvenient evening time slot, though it often ends early. Easy attendance tagging.\nDeep Learning Intro & Apps: Detailed, fluent English lectures that are accessible to non-majors. Assignments and exams involve heavy usage of generative AI (ChatGPT), which can lower self-study motivation. Grading is exceptionally generous, though administrative/exam scheduling can be a bit disorganized.",
        "keywords": ["data structures", "algorithms", "python", "complexity", "asymptotic notation", "stacks", "queues", "lists", "trees", "graphs", "sorting", "hashing"]
    },
    "CAS2103-03": {
        "name": "자료구조 (DATA STRUCTURE)",
        "workload": "Medium",
        "difficulty": "Medium",
        "professor": "김지응 (Kim Jieung)",
        "language medium": "English",
        "lecture type": "In-person",
        "major requirement": False,
        "major basic": True,
        "major elective": False, 
        "major year": 1,
        "credits": 3, 
        "time": "Wed 5, Fri 5,6",
        "location": "공D508 (EngHD508)",
        "grading scheme": "35% midterm, 40% final, 3% quiz, 17% individual assignment, 5% attendance",
        "evaluation type": "absolute",
        "prerequisites": ["Computer Programming", "Object Oriented Programming"],
        "added by in ETA": "79", 
        "review point" : "4.90/5.00",
        "review": "Highly structured masterpiece course ('KimTube') with recorded Zoom lectures and detailed notes. The professor is incredibly dedicated, answering questions 24/7 in chat rooms, though their English delivery has a heavy accent that takes time to get used to. Assignments consist of LeetCode-style problems with a slightly heavy workload. Exams are time-pressured with low averages (40-50s) but focus on algorithmic logic rather than strict syntax, allowing double-sided cheat sheets and pseudocode answers. Grading is phenomenally generous, giving out A0/A+ to 50% of the class, lowering grade cutoffs based on performance, and featuring an incredibly lenient attendance policy.",
        "review from other courses": "Software Engineering: Rushed pace with an overwhelming volume of material (1,000+ slides). The final exam focuses heavily on logic and formal verification, and assignments are challenging (e.g., Google Test, Docker). The professor's English can be difficult to follow, but grading is exceptionally generous despite low exam averages.\nCompiler Design: Heavy content and high workload with difficult exams and complex programming assignments (especially on recursion, stacks, and trees). The professor speaks very fast and stutters in English, but lecture slides are structured well, with ample examples and transparent test cases for grading.",
        "keywords": ["data structures", "algorithms", "c++", "c", "complexity", "asymptotic notation", "stacks", "queues", "lists", "trees", "graphs", "sorting", "hashing"]
    },
    "CAS2106-01": {
        "name": "컴퓨터과학입문 (INTRODUCTION TO COMPUTER SCIENCE)",
        "workload": "Medium",
        "difficulty": "Medium",
        "professor": "박상휸 (Park Sang Hyun)",
        "language medium": "Korean",
        "lecture type": "On-Off Blended (Video Recorded)",
        "major requirement": False,
        "major basic": False,
        "major elective": True, 
        "major year": 2,
        "credits": 3, 
        "time": "Tue 7 / Thu 12,13",
        "location": "공D504 (EngHD504) / Pre-recorded lecture",
        "grading scheme": "35% midterm, 35% final, 20% quiz, 10% attendance",
        "evaluation type": "relative",
        "prerequisites": [],
        "added by in ETA": "108", 
        "review point" : "3.77/5.00",
        "review": "A very light workload offering a superficial, memorization-heavy overview of computer science foundations with no assignments, consisting only of 2 quizzes and 2 exams. Test questions require regurgitating PPT slides and basic pseudocode algorithms exactly as written, though cutoffs for an A+ can be quite stingy. The course suffers from severe technical frustrations, including distorted recorded lecture audio, poor in-person microphone volume, and illegible handwriting on slides. Because grading criteria are often inconsistent or rigid, students highly recommend personally reviewing and contesting your exam papers with the TAs to get substantial score corrections.",
        "review from other courses": "Database: Very light workload with a small amount of material, but lecture quality is low and resembles basic YouTube coding hacks. Exams are a pure memorization contest with absolutely no partial credit; a single minor mistake in writing SQL queries can cut your average score in half under a relative grading scale.",
        "keywords": ["computer science", "intro", "foundations", "data storage", "data manipulation", "operating systems", "networking", "algorithms", "programming languages", "software engineering", "data abstractions", "databases", "artificial intelligence", "theory of computation"]
    },
    "CAS2109-01": {
        "name": "인터넷프로그래밍 (INTERNET PROGRAMMING)",
        "workload": "Medium",
        "difficulty": "Medium",
        "professor": "Lee, Kyong Ho",
        "language medium": "Korean",
        "lecture type": "On-Off Blended (Video Recorded)",
        "major requirement": False,
        "major basic": False,
        "major elective": True, 
        "major year": 2,
        "credits": 3, 
        "time": "Tue 5,6 / Thu 11",
        "location": "공D504 (EngHD504) / Pre-recorded lecture",
        "grading scheme": "25% midterm, 25% final, 45% individual assignment, 5% attendance",
        "evaluation type": "relative",
        "prerequisites": [],
        "added by in ETA": "47",
        "review point" : "2.69/5.00", 
        "review": "Provides a comprehensive roadmap of web essentials including HTML, CSS, JavaScript, DOM, AJAX, Node.js, Express, and SQL. You can master basic web development through the assignments, but the workload is incredibly heavy and feels like a 6-credit course. Lectures can be highly dry and sleep-inducing. Exams are notorious closed-book 'time-attacks' requiring tedious memorization of exact API spellings and handwriting entire blocks of code on paper. However, final grading is quite generous, with team projects often evaluated on video demonstrations or design tools like Figma rather than strict code submissions, pulling many grades up to an A+.",
        "review from other courses": "Database: A high-workload course where the professor primarily reads directly from the PPT slides. It features sudden surprise quizzes and a steep increase in assignment volume after the midterm. Exams are strict, pure-memorization time-attacks with low score averages and absolutely no partial credit for minor SQL query mistakes. The group project tends to heavily prioritize creative concepts over functional code execution.",
        "keywords": ["web", "internet", "html", "css", "javascript", "programming"]
    },
    "CAS3101-02": {
        "name": "운영체제 (OPERATING SYSTEM)",
        "workload": "Medium",
        "difficulty": "Medium",
        "professor": "정진규 (Jeong Jinkyu)",
        "language medium": "Korean",
        "lecture type": "In-person",
        "major requirement": True,
        "major basic": False,
        "major elective": False, 
        "major year": 3,
        "credits": 3, 
        "time": "Mon 7,8, Wed 8",
        "location": "공B5039 (EngHB039)",
        "grading scheme": "20% midterm, 25% final, 45% individual assignment, 10% attendance",
        "evaluation type": "relative",
        "prerequisites": ["Computer System", "Logic Circuit Design"],
        "added by in ETA": "169", 
        "review point" : "4.73/5.00",
        "review": "An exceptionally high-quality, passionate, and highly-rated course using xv6, though it presents a steep learning curve that can feel like it separates the top tier of students from the rest. Lectures and materials are outstanding, and the professor is widely praised as incredibly kind, supportive, and deeply dedicated to answering student questions. However, the workload is notoriously extensive and difficult, featuring rigorous programming assignments that require massive time investments—though leveraging online resources and AI tools can help you achieve an above-average score. Exams are challenging but reasonable, and final grading is highly generous and directly reflects the effort you invest.",
        "review from other courses": "Computer Systems: Highly recommended major course where the instructor lectures diligently and stays faithful to core concepts. Features exceptionally unique, high-quality, puzzle-like assignments with real-time grading feedback. Due to high assignment averages driven by widespread GPT use, the final exam is designed primarily to serve as a comprehensive assignment review.\nIntroduction to Computing: A poorly managed seminar-style class meant to showcase graduate research fields. Freshmen note that the content feels trivial, the 5-8 PM schedule is difficult, and the overall course administration is woefully inadequate.\nConnected Platform Theory and Practice: A highly unfocused course that covers a wide variety of topics, but suffers from purposeless lectures and arbitrary, meaningless projects and exams.",
        "keywords": ["os", "operating system", "processes", "cpu scheduling", "virtual memory", "paging", "threads", "synchronization", "semaphores", "file systems", "linux", "c programming"]
    },
    "CAS3102-01": {
        "name": "컴퓨터아키텍쳐 (ARCHITECTURE OF COMPUTERS)",
        "workload": "Medium",
        "difficulty": "Medium",
        "professor": "이경우 (Lee Kyoungwoo)",
        "language medium": "Korean",
        "lecture type": "On-Off Blended (Flipped Classroom)",
        "major requirement": True,
        "major basic": False,
        "major elective": False, 
        "major year": 3,
        "credits": 3, 
        "time": "Mon 5,6 / Wed 6",
        "location": "공D504 (EngHD504) / Pre-recorded lecture",
        "grading scheme": "0% midterm, 20% final, 40% quiz, 40% individual assignment",
        "evaluation type": "relative",
        "prerequisites": ["Logic Circuit Design"],
        "added by in ETA": "80", 
        "review point" : "4.50/5.00",
        "review": "The professor is highly dedicated, passionate, and very accommodating, making it an excellent and comfortable choice for double majors or transfer students. The workload is relatively light, featuring 4 straightforward assignments (MIPS Assembly, Processor Design, Python Cache Implementation, and Scoreboarding) that are beginner-friendly and easier than 2000-level data structures. The course content, difficulty, TAs, and quiz styles are almost identical to Professor Lee Kyoungwoo's section. However, there can be a discrepancy between lectures and the 5 quizzes, making the TA review sessions critical. The final exam can feel overwhelming due to scheduling conflicts, but the final grading is exceptionally generous.",
        "review from other courses": "Cloud Computing: A decent class with a textbook teaching style, manageable workload, and highly beneficial hands-on practice. However, assignment and final mini-project grading criteria are highly subjective, with arbitrary point deductions for a 'lack of detail' despite claims of completion-based grading. Exams can be highly frustrating as they focus on testing obscure, unimportant slide details and trivial matters rather than core programming or practical concepts.",
        "keywords": ["architecture", "computer architecture", "assembly", "mips", "isa", "pipelining", "hazards", "caches", "virtual memory", "out-of-order execution", "tomasulo", "superscalar", "multi-threading", "multi-core"],
        "notes": "Flipped classroom layout requires pre-class video viewing before live participation."
    },
    
    "CAS4102-01-00": {
        "name": "인공지능종합설계 (AI Capstone Design)",
        "workload": "Medium",
        "difficulty": "Medium",
        "professor": "이봉신 (Bongshin Lee)",
        "language medium": "Korean (no explicit English label)",
        "lecture type": "In-person",
        "major requirement": True,
        "major basic": False,
        "major elective": False,
        "major year": 3,
        "credits": 3,
        "time": "Wed 4:00–5:00 PM, Fri 4:00–6:00 PM",
        "location": "공D508 (EngHD508)",
        "grading scheme": "70% team projects, 10% attendance, 20% other",
        "evaluation type": "absolute",
        "prerequisites": [],
        "added by in ETA": "40",
        "review": "",
        "review from other courses": "Deducts marks despite unclear assignment requirements, passionate about teaching and receptive to feedback, very strict attendance policy, provides vague project instructions while expecting high-quality work.",
        "keywords": ["capstone design", "team project", "AI system design", "research trends", "exhibition"]
    },
    
    "CAS4108-01-00": {
        "name": "데이터프라이버시학 (Data Privacy)",
        "workload": "Medium",
        "difficulty": "Medium",
        "professor": "노일버트 (Albert No)",
        "language medium": "English",
        "lecture type": "In-person",
        "major requirement": False,
        "major basic": False,
        "major elective": True,
        "major year": 3,
        "credits": 3,
        "time": "Tue 12:00–1:00 PM, Thu 1:00–3:00 PM",
        "location": "공D508 (EngHD508)",
        "grading scheme": "45% midterm, 45% final, 10% individual assignments",
        "evaluation type": "absolute",
        "prerequisites": ["Probability theory", "Linear algebra", "Calculus"],
        "added by in ETA": "37",
        "review": "responsive to questions, good teaching quality, high difficulty, professor good at explaining, test questions are mostly proof questions, taking courses like probability theory, linear algebra and calculus will help a lot, fair grading distribution",
        "review from other courses": "",
        "keywords": ["differential privacy", "generative diffusion models", "large language models", "privacy", "federated learning", "memorization", "unlearning", "watermarking"]
    },

    "CAS4109-01-00": {
        "name": "컴퓨터보안학 (Computer Security)",
        "workload": "High",
        "difficulty": "High",
        "professor": "송도경 (Dokyung Song)",
        "language medium": "English",
        "lecture type": "On-Off Blended (Flipped Classroom)",
        "major requirement": False,
        "major basic": False,
        "major elective": True,
        "major year": 3,
        "credits": 3,
        "time": "Tue 3:00–4:00 PM, Thu 8:00–10:00 PM",
        "location": "공D408 (EngHD408) / online video (duplicate registration not allowed)",
        "grading scheme": "20% midterm, 20% final, 55% individual assignments, 5% attendance",
        "evaluation type": "absolute",
        "prerequisites": ["Operating Systems", "Computer Architecture"],
        "added by in ETA": "87",
        "review": "",
        "review from other courses": "lots of assignments with high technical difficulty but class content is interesting, professor mostly just reads through powerpoint slides, professor pronunciation is spot on, gives good grades",
        "keywords": ["computer security", "threat modeling", "access control", "authentication", "cryptography", "software security", "hardware security", "attack payloads", "defensive programming"]
        
    },

    "CAS4119-01-00" : {
        "name": "멀티코어및GPU프로그래밍 (Multi-core and GPU Programming)",
        "workload": "High",
        "difficulty": "High",
        "professor": "박영준 (Yongjun Park)",
        "language medium": "English",
        "lecture type": "In-person",
        "major requirement": False,
        "major basic": False,
        "major elective": True,
        "major year": 3,
        "credits": 3,
        "time": "Wed 11:00–12:00 PM, Fri 11:00–1:00 PM",
        "location": "공D504 (EngHD504)",
        "grading scheme": "30% midterm, 40% final, 25% individual assignments, 5% attendance",
        "evaluation type": "absolute",
        "prerequisites": ["OS (Operating Systems)", "CA (Computer Architecture)", "Algorithm"],
        "added by in ETA": "97",
        "review": "practical course, heavy load but you learn a lot, professor gives good grades, open book exams with hand coding",
        "review from other courses": "",
        "keywords": ["multi-core", "GPU", "CUDA", "Pthread", "openMP", "parallel programming", "matrix multiplication", "reduction", "deep learning kernels"]
    },
    
    "CAS4127-01-00" : {
        "name": "인간-인공지능상호작용학 (Human-AI Interaction)",
        "workload": "High",
        "difficulty": "Medium",
        "professor": "김대현 (Daehyun Kim)",
        "language medium": "English",
        "lecture type": "In-person",
        "major requirement": False,
        "major basic": False,
        "major elective": True,
        "major year": 3,
        "credits": 3,
        "time": "Tue 10:00–12:00 PM, Thu 9:00–10:00 AM",
        "location": "공D408 (EngHD504)",
        "grading scheme": "40% individual assignments, 30% team projects, 10% attendance, 20% participation",
        "evaluation type": "absolute",
        "prerequisites": [],
        "added by in ETA": "41",
        "review": "",
        "review from other courses": "very generous with grades, passionate teaching, open and adaptive to course feedback from students, professor is good at answering questions",
        "keywords": ["human-AI interaction", "HCI", "AI collaboration", "user modeling", "simulating human behavior", "LLM", "creativity", "education"]
    },

    "CAS4133-01-00" : {
        "name": "거대언어모델학 (Large Language Models)",
        "workload": "High",
        "difficulty": "High",
        "professor": "김재형 (Jaehyung Kim)",
        "language medium": "English",
        "lecture type": "In-person",
        "major requirement": False,
        "major basic": False,
        "major elective": True,
        "major year": 3,
        "credits": 3,
        "time": "Mon 1:00–3:00 PM, Wed 2:00–3:00 PM",
        "location": "공D508 (EngHD508)",
        "grading scheme": "20% midterm, 30% final, 40% individual assignments, 10% attendance",
        "evaluation type": "absolute",
        "prerequisites": ["Machine learning", "Deep learning"],
        "added by in ETA": "93",
        "review": "professor gives good grades, tough assignments, professor struggles with english, assignments include modifying skeleton code and a free topic project, midterms only consist of True/False and MCQ questions, overall interesting class content",
        "review from other courses": "",
        "keywords": ["large language models", "LLM", "pre-training", "scaling laws", "alignment", "instruction tuning", "RLHF", "RAG", "AI agents", "multi-modality"]
    },

    "CAS4150-01-00" : {
        "name": "데이터시각화입문 (Introduction to Data Visualization)",
        "workload": "Medium",
        "difficulty": "Medium",
        "professor": "강민석 (Minsuk Kang)",
        "language medium": "English",
        "lecture type": "In-person",
        "major requirement": False,
        "major basic": False,
        "major elective": True,
        "major year": 3,
        "credits": 3,
        "time": "Tue 12:00–1:00 PM, Thu 3:00–5:00 PM",
        "location": "동영상콘텐츠 / 공D408 (EngHD408) (video content + room D408)",
        "grading scheme": "25% midterm, 25% final, 20% individual assignments, 20% team projects, 10% other",
        "evaluation type": "absolute",
        "prerequisites": ["Basic programming knowledge", "HTML/CSS (recommended)"],
        "added by in ETA": "81",
        "review": "professor is friendly and generous with grades, exams include one hand coding question and the rest is PPT memorization, high quality lectures, individual assignments are manageable but team assignments are taxing",
        "review from other courses": "",
        "keywords": ["data visualization", "interactive visualization", "JavaScript", "D3", "Tableau", "exploratory data analysis", "human-centered design", "perception", "color"]
    },
    
    "MAT2013-03-00" : {
        "name": "확률통계학 (Probability and Statistics)",
        "workload": "Medium",
        "difficulty": "Medium",
        "professor": "최장열 (Jangyeol Choi)",
        "language medium": "Korean (no explicit English label)",
        "lecture type": "In-person",
        "major requirement": True,
        "major basic": True,
        "major elective": False,
        "major year": 2,
        "credits": 3,
        "time": "Mon 4:00–6:00 PM, Wed 5:00–6:00 PM",
        "location": "공학월170E",
        "grading scheme": "40% midterm, 40% final, 10% quiz, 10% attendance",
        "evaluation type": "relative",
        "prerequisites": [],
        "added by in ETA": "93",
        "review": "good teaching, cheatsheet allowed only for exams, can be absent for 9 class hours with no penalty, exams include half proofing questions and half calculation questions, stricter scoring method, quizzes are relatively easy compared to exams, past year questions are provided and helpful for exams and quizzes",
        "review from other courses": "",
        "keywords": ["probability", "statistics", "random variables", "probability distributions", "expectation", "conditional probability", "joint density", "marginal density", "MGF"]
    }, 

    "MAT2013-04-00" : {
        "name": "확률통계학 (Probability and Statistics)",
        "workload": "Medium",
        "difficulty": "Medium",
        "professor": "김현정 (Hyunjung Kim)",
        "language medium": "Korean (no explicit English label)",
        "lecture type": "In-person",
        "major requirement": True,
        "major basic": True,
        "major elective": False,
        "major year": 2,
        "credits": 3,
        "time": "Fri 9:00 AM – 12:00 PM",
        "location": "공D408 (EngHD408)",
        "grading scheme": "40% midterm, 40% final, 20% individual assignments",
        "evaluation type": "relative",
        "prerequisites": [],
        "added by in ETA": "74",
        "review": "professor is nice, lecture slides, notes, videos, assignment sample solutions are posted on learnus making it easy to study, moderate test difficulty although partical scores are given, past year papers are provided",
        "review from other courses": "",
        "keywords": ["probability", "statistics", "random variables", "discrete distributions", "continuous distributions", "central limit theorem", "expected value", "variance", "regression analysis"]
    },

    "MAT2011-03-00" : {
        "name": "선형대수와그응용 (Linear Algebra and Its Applications)",
        "workload": "Medium",
        "difficulty": "Medium",
        "professor": "최장열 (Jangyeol Choi)",
        "language medium": "Korean (no explicit English label)",
        "lecture type": "In-person",
        "major requirement": True,
        "major basic": True,
        "major elective": False,
        "major year": 1,
        "credits": 3,
        "time": "Mon 6:00–8:00 PM, Wed 7:00–8:00 PM",
        "location": "공학월170E",
        "grading scheme": "40% midterm, 40% final, 10% quiz, 10% attendance",
        "evaluation type": "relative",
        "prerequisites": [],
        "added by in ETA": "92",
        "review": "good teaching, open book exams, can be absent for 9 class hours with no penalty, exams include half proofing questions and half calculation questions, stricter scoring method, quizzes are relatively easy compared to exams",
        "review from other courses": "",
        "keywords": ["linear algebra", "vector space", "linear independence", "basis", "linear operators", "matrices", "eigenvalues", "eigenvectors"]
    },

    "CAS4151-01-00" : {
        "name": "SW-AI비즈니스응용설계 (SW-AI Business Application Design)",
        "workload": "Medium",
        "difficulty": "Medium",
        "professor": "김현수 (Hyunsoo Kim)",
        "language medium": "Korean (no explicit English label)",
        "lecture type": "In-person",
        "major requirement": False,
        "major basic": False,
        "major elective": True,
        "major year": 4,
        "credits": 3,
        "time": "Wed 2:00–3:00 PM, Fri 2:00–4:00 PM",
        "location": "공A343 / 공D507 (EngHA343/EngHD507)",
        "grading scheme": "50% individual assignments, 20% attendance, 30% other",
        "evaluation type": "absolute",
        "prerequisites": ["Basic coding skills (coding methods not taught in class)"],
        "added by in ETA": "31",
        "review": "no exams, only presentations for midterms and finals, professor is responsive and helpful, aim of class is to create your own startup product, certain level of coding experience especially in web development is required, generous with grades as long as you put in the effort",
        "review from other courses": "",
        "keywords": ["business", "AI", "SW", "problem solving", "market testing", "MVP", "POC", "growth hacking", "self-directed learning"]
    }, 

    "CAS4160-01-00" : {
        "name": "강화학습 (Reinforcement Learning)",
        "workload": "High",
        "difficulty": "High",
        "professor": "이영운 (Youngwoon Lee)",
        "language medium": "English",
        "lecture type": "In-person",
        "major requirement": False,
        "major basic": False,
        "major elective": True,
        "major year": 3,
        "credits": 3,
        "time": "Wed 1:00–2:00 PM, Fri 7:00–9:00 PM",
        "location": "공D504 (EngHD504) / online video (duplicate registration not allowed)",
        "grading scheme": "30% midterm, 30% final, 35% individual assignments, 5% other",
        "evaluation type": "absolute",
        "prerequisites": ["Machine Learning", "Deep Learning", "PyTorch"],
        "added by in ETA": "110",
        "review": "high quality lecture and assignments, professor is passionate, generous with grades, uses recap slides in class for revision, overall perfect course, will regret if you dont take this professors class at least once in your lifetime",
        "review from other courses": "",
        "keywords": ["reinforcement learning", "deep RL", "policy gradients", "actor-critic", "PPO", "Q-learning", "offline RL", "model-based RL", "inverse RL", "RLHF", "PyTorch"]
    }, 

    "CAS4131-01-00" : {
        "name": "커넥티드플랫폼이론과실제 (THEORY AND PRACTICE OF CONNECTED PLATFORM)",
        "workload": "Medium",
        "difficulty": "Medium",
        "professor": "이경우 (Kyoungwoo Lee)",
        "language medium": "Korean (no explicit English label)",
        "lecture type": "In-person",
        "major requirement": False,
        "major basic": False,
        "major elective": True,
        "major year": 3,
        "credits": 3,
        "time": "Mon 11:00 AM – 2:00 PM",
        "location": "공D508 (EngHD508)",
        "grading scheme": "30% midterm, 30% final, 20% individual assignment, 20% team project",
        "evaluation type": "absolute",
        "prerequisites": [],
        "added by in ETA": "25",
        "review": "",
        "review from other courses": "",
        "keywords": ["webOS", "LG Smart TV", "embedded platform", "connected devices", "voice recognition", "AI", "open source", "DevOps", "media"]
    }
}
